version: "3.3"
services:
  app:
    container_name: frx-project
    image: frx-project
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres